Traceback (most recent call last):
  File "/home/ubuntu/TACT/app.py", line 1, in <module>
    import discord  # type: ignore
    ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'discord'
[2024-11-14 15:07:40] [INFO    ] discord.client: logging in using static token
[2024-11-14 15:07:41] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e0921e254d1ca6ac33a61a6f0e32061d).
[2024-11-14 16:54:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-14 17:03:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-14 18:03:36] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-14 19:58:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-14 20:49:23] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-14 23:25:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 00:02:12] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 00:51:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 02:46:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 05:54:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 08:29:04] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 09:07:32] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 09:41:00] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 11:10:43] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 12:25:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 13:04:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 13:52:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 14:44:26] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 14:57:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 15:44:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 16:27:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 17:52:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 19:10:17] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 20:05:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 20:12:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 22:58:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-15 23:29:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 00:05:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 01:45:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 02:06:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 03:25:15] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 03:59:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 05:51:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 08:05:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 09:00:47] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 10:38:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 11:46:02] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 13:03:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 14:51:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 16:06:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 17:43:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 18:29:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 20:28:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-16 22:47:48] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 02:13:44] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 03:48:40] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 07:01:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 08:50:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 10:01:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 12:02:49] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 15:12:13] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 17:52:41] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 18:57:14] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 20:32:28] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 21:51:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-17 23:37:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 02:08:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 03:55:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 05:17:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 07:38:21] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 09:49:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 11:15:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 11:50:09] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 12:35:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 12:58:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 12:59:38] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 13:01:08] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 16:48:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 18:13:45] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 18:14:22] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 18:16:06] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 19:35:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-18 21:19:20] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "bump" is not found
[2024-11-18 23:18:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 00:23:55] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 01:08:59] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 03:54:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 04:27:46] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 05:23:07] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 06:19:34] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session e0921e254d1ca6ac33a61a6f0e32061d.
[2024-11-19 06:26:01] [WARNING ] discord.gateway: Can't keep up, shard ID None websocket is 15.2s behind.
[2024-11-19 06:26:01] [WARNING ] discord.gateway: Can't keep up, shard ID None websocket is 15.3s behind.
[2024-11-20 16:53:02] [INFO    ] discord.client: logging in using static token
[2024-11-20 16:53:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 57252a7f9defb411d47f6bf1a497be79).
[2024-11-20 17:18:58] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
/home/ubuntu/TACT/app.py:512: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.utcnow()
/home/ubuntu/TACT/app.py:334: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.utcnow()
[2024-11-20 17:46:39] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-20 18:31:32] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-20 18:50:11] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-20 20:45:57] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-20 22:04:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-20 22:14:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-20 22:40:39] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-20 23:24:51] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 02:05:11] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 05:31:03] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 06:49:39] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-21 06:59:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 07:54:24] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 09:13:33] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 10:20:15] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-21 10:58:27] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 12:08:54] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 13:55:35] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 17:01:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 20:48:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-21 21:48:19] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-22 01:28:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-22 04:50:05] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 57252a7f9defb411d47f6bf1a497be79.
[2024-11-22 05:14:55] [WARNING ] discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
[2024-11-22 08:47:53] [INFO    ] discord.client: logging in using static token
[2024-11-22 08:47:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: aec54611947434b5f192102b9cf42cbc).
[2024-11-22 08:48:46] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-22 08:50:21] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
/home/ubuntu/TACT/app.py:334: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.utcnow()
/home/ubuntu/TACT/app.py:512: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.utcnow()
[2024-11-22 09:53:53] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session aec54611947434b5f192102b9cf42cbc.
[2024-11-22 11:05:59] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'leaderboard'
Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/app.py", line 120, in leaderboard
    await interaction.response.send_message(embed=embed)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/interactions.py", line 827, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/TACT/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'leaderboard' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024-11-22 13:01:50] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session aec54611947434b5f192102b9cf42cbc.
[2024-11-22 13:05:42] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session aec54611947434b5f192102b9cf42cbc.
